CREATE TABLE IF NOT EXISTS requests
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app        VARCHAR(127)                NOT NULL,
    uri        VARCHAR(255)                NOT NULL,
    ip         VARCHAR(45)                 NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);